### PR TITLE
Extenduser

### PR DESCRIPTION
**Pull request by Grunze1s**
Created a user model with username field as phone number(char field is made).
Added uuid for user which is auto generated and is generated using uuid4 of uuid package of python.
Closes: #2

### CODE REVIEW

**Comment by shovan777** [comment]
how is the uuid being generated??

**Comment by shovan777** [comment]
@Grunze1s which is the primary field in the user model?

**Comment by Grunze1s** [comment]
It is auto generate using the [uuid field](https://docs.djangoproject.com/en/3.0/ref/models/fields/#uuidfield) of djagno which uses the [uuid package](https://docs.python.org/3/library/uuid.html#uuid.uuid4) of python. Which auto generates the random id using the fields described [here](https://docs.python.org/3/library/uuid.html#uuid.UUID.fields)

**Comment by Grunze1s** [comment]
Primary key is the auto generated Integer field .

**Comment by shovan777** [comment]
can't we make the uuid or phone number as primary field? what is the use of having uuid if you have a seperate primary id field?

**Comment by Grunze1s** [comment]
Uuid id is randomly generated, which is not generated using phone number. Since phone number and uuid are present is same table they are both linked with each other. Also the Uuid is a unique field similar to the primary key.

**Comment by Grunze1s** [comment]
> can't we make the uuid or phone number as primary field? what is the use of having uuid if you have a seperate primary id field?

We can make uuid as a primary key.

**Comment by shovan777** [comment]
> > can't we make the uuid or phone number as primary field? what is the use of having uuid if you have a seperate primary id field?
> 
> We can make uuid as a primary key.

should we do that then, I just don't see having another field? Since phone number is itself unique why is the uuid then necessary?

**Comment by Grunze1s** [comment]
> > > can't we make the uuid or phone number as primary field? what is the use of having uuid if you have a seperate primary id field?
> > 
> > 
> > We can make uuid as a primary key.
> 
> should we do that then, I just don't see having another field? Since phone number is itself unique why is the uuid then necessary?

uuid is necessary so that the other user don't have to the access to phone number but have access to the uuid of other user. we could use primary key of django instead of uuid but primay key of django is simple increment of number so i think this will be vulnerable. Rather we could change primary key of djagno to uuid field.

**Comment by shovan777** [comment]
> > > > can't we make the uuid or phone number as primary field? what is the use of having uuid if you have a seperate primary id field?
> > > 
> > > 
> > > We can make uuid as a primary key.
> > 
> > 
> > should we do that then, I just don't see having another field? Since phone number is itself unique why is the uuid then necessary?
> 
> uuid is necessary so that the other user don't have to the access to phone number but have access to the uuid of other user. we could use primary key of django instead of uuid but primay key of django is simple increment of number so i think this will be vulnerable. Rather we could change primary key of djagno to uuid field.

that is good then, lets make that change then merge.

**Comment by Grunze1s** [comment]
ok

**Pull request merged**
